name: cops
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - appdirs=1.4.4
  # - appnope=0.1.2
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=38.0.4
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - fftw=3.3.9
  - flatbuffers=2.0.0
  - flit-core=3.6.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.4
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.4.9
  - jupyter_core=5.2.0
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.87.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  # - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - matplotlib=3.6.3
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.1
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=22.0
  - pandas=1.4.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.3.0
  - pip=22.3.1
  - platformdirs=2.5.2
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.16
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.8
  - pytz=2022.7
  - pyzmq=23.2.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.10.0
  - setuptools=65.6.3
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.40.1
  - stack_data=0.2.0
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.10.0
  - tensorflow-base=2.10.0
  - tensorflow-estimator=2.10.0
  - termcolor=2.1.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wcwidth=0.2.5
  - werkzeug=2.2.2
  - wheel=0.35.1
  - wrapt=1.14.1
  - xz=5.2.10
  - yarl=1.8.1
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - joblib==1.2.0
    - pulp==2.7.0
    - scikit-learn==1.2.2
    - threadpoolctl==3.1.0
    - tqdm==4.64.1
